- name: Configure Production VM
  hosts: azure
  user: fmacke200
  become: yes

  vars:
    myResourceGroup: coursework_2
    myVM: coursework2-production

  tasks:

    - stat:
        path: /home/fmacke200/kubernetes.sh
      register: result

    - name: Copy kubernetes.sh to Production VM
      copy:
        src: ../setup_scripts/kubernetes.sh
        dest: /home/fmacke200/kubernetes.sh
      when: result.stat.exists == false

    - name: Set kubernetes.sh permissions
      command: chmod +x /home/fmacke200/kubernetes.sh

    - name: Run Kubernetes installation script
      command: sudo /home/fmacke200/kubernetes.sh
