- name: Create Production VM
  hosts: localhost
  connection: local

  vars:
    myResourceGroup: coursework_2
    myVnet: coursework_2-production-vnet
    mySubnet: coursework_2-production-subnet
    myPublicIP: coursework_2-production-publicip
    myNIC: coursework_2-production-nic
    myNetworkSecurityGroup: coursework_2-production-nsg
    myVM: coursework_2-production
    mySSHkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/V60DWqpC+F3RG9+iHx0z8aGo4zBrY4QMEbxKN9wZduijrBXgmGUjkTyQgZ6jqXVdSz8+FAgn105LTxNdSAkoS4guvg6VI67dQNNZnjONEJ0cSPi9cJxb0N4T4bIQouZTU8MXWkt3f35cwDNIfjTa/wuRsbU8ednHI+yfX3fyydbC4cPjO0Z733AciInX2IWxwdPrfwvLpd1JiH+6LALA5A4OLEpJwy0w6bLI/sXL6O5AomPHsolZnWv2+JNtwvCPDW7KMdKWFUorPG1IB9DBp5I8NkYaaBKo93num94EKrf97Xa+wVIZ+9WDqBlEyS2sGfmdowC3IzDxX3n5jW0T fmacke200@coursework2-build

  tasks:

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ myResourceGroup }}"
        name: "{{  myVnet }}"
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ myResourceGroup }}"
        name: "{{ mySubnet }}"
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ myVnet }}"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ myResourceGroup }}"
        allocation_method: Static
        name: "{{ myPublicIP }}"
      register: output_ip_address

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ myResourceGroup}}"
        name: "{{ myNetworkSecurityGroup }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ myResourceGroup }}"
        name: "{{ myNIC }}"
        virtual_network: "{{ myVnet }}"
        subnet: "{{ mySubnet }}"
        public_ip_name: "{{ myPublicIP }}"
        security_group: "{{ myNetworkSecurityGroup }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ myResourceGroup }}"
        name: "{{ myVM }}"
        vm_size: Standard_D2s_v3
        admin_username: fmacke200
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/fmacke200/.ssh/authorized_keys
            key_data: "{{ mySSHkey }}"
        network_interfaces: "{{ myNIC }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: '16.04-LTS'
          version: latest

    - name: Print Public IP for VM which will be created
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."
